-- Threat Intelligence Platform — initial schema
-- Generated by Drizzle Kit

CREATE TYPE "asset_type" AS ENUM ('ip', 'domain', 'cidr', 'url');
CREATE TYPE "severity" AS ENUM ('critical', 'high', 'medium', 'low', 'none');
CREATE TYPE "vuln_status" AS ENUM ('open', 'acknowledged', 'remediated', 'false_positive');
CREATE TYPE "alert_type" AS ENUM ('vulnerability', 'ioc_match', 'scan_complete', 'feed_update');
CREATE TYPE "alert_severity" AS ENUM ('critical', 'high', 'medium', 'low', 'info');
CREATE TYPE "ioc_type" AS ENUM ('ip', 'domain', 'url', 'hash');
CREATE TYPE "ioc_verdict" AS ENUM ('malicious', 'suspicious', 'clean', 'unknown');
CREATE TYPE "feed_status" AS ENUM ('running', 'completed', 'failed');

CREATE TABLE IF NOT EXISTS "users" (
  "id"            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "email"         varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "created_at"    timestamp DEFAULT now() NOT NULL,
  "updated_at"    timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "assets" (
  "id"           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"      uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "type"         "asset_type" NOT NULL,
  "value"        varchar(512) NOT NULL,
  "label"        varchar(255),
  "tags"         jsonb DEFAULT '[]',
  "active"       boolean DEFAULT true NOT NULL,
  "last_scanned" timestamp,
  "created_at"   timestamp DEFAULT now() NOT NULL,
  UNIQUE ("user_id", "value")
);

CREATE TABLE IF NOT EXISTS "vulnerabilities" (
  "id"                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "cve_id"            varchar(30) UNIQUE NOT NULL,
  "title"             text,
  "description"       text NOT NULL,
  "severity"          "severity" NOT NULL,
  "cvss_score"        numeric(4, 2),
  "cvss_vector"       varchar(100),
  "published_at"      timestamp NOT NULL,
  "modified_at"       timestamp,
  "affected_products" jsonb DEFAULT '[]',
  "references"        jsonb DEFAULT '[]',
  "raw_data"          jsonb,
  "created_at"        timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "asset_vulnerabilities" (
  "id"               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "asset_id"         uuid NOT NULL REFERENCES "assets"("id") ON DELETE CASCADE,
  "vulnerability_id" uuid NOT NULL REFERENCES "vulnerabilities"("id") ON DELETE CASCADE,
  "status"           "vuln_status" DEFAULT 'open' NOT NULL,
  "discovered_at"    timestamp DEFAULT now() NOT NULL,
  "updated_at"       timestamp DEFAULT now() NOT NULL,
  UNIQUE ("asset_id", "vulnerability_id")
);

CREATE TABLE IF NOT EXISTS "ioc_records" (
  "id"           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "indicator"    varchar(512) UNIQUE NOT NULL,
  "type"         "ioc_type" NOT NULL,
  "verdict"      "ioc_verdict" NOT NULL,
  "score"        integer DEFAULT 0,
  "sources"      jsonb DEFAULT '[]',
  "last_checked" timestamp DEFAULT now() NOT NULL,
  "expires_at"   timestamp NOT NULL,
  "created_at"   timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "alerts" (
  "id"         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"    uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "asset_id"   uuid REFERENCES "assets"("id") ON DELETE SET NULL,
  "type"       "alert_type" NOT NULL,
  "severity"   "alert_severity" NOT NULL,
  "title"      varchar(500) NOT NULL,
  "details"    jsonb NOT NULL,
  "read_at"    timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "feed_syncs" (
  "id"                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "feed_type"         varchar(50) NOT NULL,
  "status"            "feed_status" DEFAULT 'running' NOT NULL,
  "started_at"        timestamp DEFAULT now() NOT NULL,
  "completed_at"      timestamp,
  "records_processed" integer DEFAULT 0,
  "records_added"     integer DEFAULT 0,
  "error"             text,
  "metadata"          jsonb
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS "assets_user_id_idx"    ON "assets" ("user_id");
CREATE INDEX IF NOT EXISTS "assets_value_idx"      ON "assets" ("value");
CREATE INDEX IF NOT EXISTS "av_asset_id_idx"       ON "asset_vulnerabilities" ("asset_id");
CREATE INDEX IF NOT EXISTS "alerts_user_id_idx"    ON "alerts" ("user_id");
CREATE INDEX IF NOT EXISTS "alerts_created_at_idx" ON "alerts" ("created_at" DESC);
CREATE INDEX IF NOT EXISTS "alerts_user_sev_idx"   ON "alerts" ("user_id", "severity");
CREATE INDEX IF NOT EXISTS "ioc_expires_at_idx"    ON "ioc_records" ("expires_at");
